### PR TITLE
double ubuntu-minimal, isc-dhcp-client already included inside

### PR DESCRIPTION
**Pull request by Nerten**
Small pretty changes for ubuntu packages

### CODE REVIEW

**Comment by umiddelb** [comment]
Thank you for the PR. I believe there is much room for refactoring inside of `common/common-functions.sh`. I'm fine with all commits, except of [a790602](https://github.com/umiddelb/z2d/pull/3/commits/a7906020364ff6fc2b4b4a42bb0b3c7010a1aafc). I needed to hard-wire this kernel version, because subsequent versions don't have aufs support included (and you cannot easily switch it on again). Docker will run without aufs support but it isn't that much fun.

**Comment by Nerten** [comment]
Oh, thank you. I going to figure it out with docker. I'll to revert back this commit. I saw your discussion about aufs, but missed to keep it in my mind.

**Comment by Nerten** [comment]
Now this pull request ready for merge.

**Comment by umiddelb** [comment]
Thank you. You have introduced `sudo usermod -aG docker $SUDO_USER`. I've used this before but experienced that `$SUDO_USER` might be empty in non-interactive environments. So I've reverted this back. 

And as long as `debian` or `ubuntu` are still hard-wired in the `...-02.sh` scripts, it doesn't hurt that much.

**Comment by Nerten** [comment]
Ok, reverted it too. Sadly there is no working method to find current username. But now I am working on feature with system settings config which may help.

**Comment by umiddelb** [comment]
Thank you!

**Pull request merged**
